/* eslint-disable */
/* global WebImporter */
/**
 * Parser for hero-login. Base: hero. Source: https://www.truist.com/
 * Selectors validated against migration-work/block-context/hero-login/source.html
 *
 * Output (per blocks/hero-login/README.md):
 *   Row 1: background image (img.hero-login-bg-image)
 *   Row 2: <p>eyebrow</p> (.hero-title), <h1> (.hero-subtitle), body (.hero-description p),
 *          CTAs: first as <strong><a>, others as <em><a>
 *   Row 3 (optional): sign-in panel plain links (form inputs are generated by block JS)
 */
function cleanLink(document, a) {
  const link = document.createElement('a');
  link.href = a.getAttribute('href') || a.href;
  const clone = a.cloneNode(true);
  clone.querySelectorAll('.sr-only, .visually-hidden, img, svg').forEach((n) => n.remove());
  link.textContent = clone.textContent.replace(/\s+/g, ' ').trim();
  return link;
}

export default function parse(element, { document }) {
  const bgImage = element.querySelector('img.hero-login-bg-image, .hero-login-left-container > img, .jumbotron img');

  const content = element.querySelector('.hero-content') || element;
  const titleEl = content.querySelector('.hero-title');
  const subtitleEl = content.querySelector('.hero-subtitle');
  const headingEl = content.querySelector('h1, h2, h3');

  const contentCell = [];

  // Eyebrow + headline. Source uses spans: .hero-title (eyebrow) and .hero-subtitle (headline).
  if (titleEl && subtitleEl) {
    const eyebrow = document.createElement('p');
    eyebrow.textContent = titleEl.textContent.trim();
    contentCell.push(eyebrow);
    const h1 = document.createElement('h1');
    h1.textContent = subtitleEl.textContent.trim();
    contentCell.push(h1);
  } else if (headingEl || titleEl || subtitleEl) {
    const src = headingEl || titleEl || subtitleEl;
    const h1 = document.createElement('h1');
    h1.textContent = src.textContent.trim();
    contentCell.push(h1);
  }

  // Body copy (keep footnote sup links; drop screen-reader-only text)
  const description = content.querySelector('.hero-description');
  if (description) {
    description.querySelectorAll('.sr-only, .visually-hidden').forEach((n) => n.remove());
    const paras = [...description.querySelectorAll('p')];
    if (paras.length) contentCell.push(...paras);
    else if (description.textContent.trim()) {
      const p = document.createElement('p');
      p.append(...description.childNodes);
      contentCell.push(p);
    }
  }

  // CTAs: first = primary (strong), rest = secondary (em)
  const ctas = [...content.querySelectorAll('.hero-btn-container a, a.btn-cta')]
    .filter((a, i, arr) => arr.indexOf(a) === i);
  ctas.forEach((a, i) => {
    const p = document.createElement('p');
    const wrap = document.createElement(i === 0 ? 'strong' : 'em');
    wrap.append(cleanLink(document, a));
    p.append(wrap);
    contentCell.push(p);
  });

  if (!bgImage && !contentCell.length) {
    element.replaceWith(...element.childNodes);
    return;
  }

  const cells = [];
  if (bgImage) cells.push([bgImage]);
  cells.push([contentCell]);

  // Optional Row 3: sign-in panel helper links (no form inputs)
  const login = element.querySelector('.login-component, .hero--login-menu--row');
  if (login) {
    const linksCell = [];
    const seen = new Set();
    login.querySelectorAll('a[href]').forEach((a) => {
      const href = a.getAttribute('href');
      if (!href || href.startsWith('#') || seen.has(href)) return;
      seen.add(href);
      const p = document.createElement('p');
      // Preserve "Need a user ID?" lead-in text from the same paragraph
      const para = a.closest('p');
      const strong = para && para.querySelector('strong');
      if (strong && strong.textContent.trim()) {
        p.append(`${strong.textContent.trim()} `);
      }
      p.append(cleanLink(document, a));
      linksCell.push(p);
    });
    if (linksCell.length) cells.push([linksCell]);
  }

  const block = WebImporter.Blocks.createBlock(document, { name: 'hero-login', cells });
  element.replaceWith(block);
}
